[package]
name = "simag_networking"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10"
libp2p = "^0.23.0"
# serde = "^1.0.0"
smol = "0.3.3"
once_cell = "^1.3.0"

# internal:
# simag_core = { path = "../simag_core" }
