[package]
name = "simag_networking"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
config = "0.10"
crossbeam = "0.7.3"
ed25519-dalek = { version = "1.0.0-pre.4", optional = true }
libp2p = "^0.23.0"
once_cell = "^1.3.0"
rand = { version = "0.7", optional = true }
# serde = "^1.0.0"
smol = "0.3.3"

# internal:
# simag_core = { path = "../simag_core" }

[[bin]]
name = "key-manager"
path = "bin/key_manager.rs"
required-features = ["key-manager"]

[features]
key-manager = ["ed25519-dalek", "rand"]
