[package]
name = "simag_networking"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
config = "0.10"
crossbeam = "0.7.3"
ed25519-dalek = { version = "1.0", optional = true }
env_logger = "0.7.1"
futures_codec = "0.4.1"
libp2p = { version = "0.24.0", features = [
    "deflate",
    "dns",
    "identify",
    "kad",
    "gossipsub",
    "mplex",
    "noise",
    "secio",
    "secp256k1",
    "tcp-async-std",
    "tcp-tokio",
    "yamux"
] }
log = "0.4"
once_cell = "1.4"
rand = "0.7"
smallvec = "1.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["macros", "rt-threaded", "sync", "time"] }
unsigned-varint = { version = "0.5.0", features = ["futures-codec"] }
uuid = { version = "0.8.1", features = ["v4", "v5"]}

# internal:
# simag_core = { path = "../simag_core" }

[[bin]]
name = "key-manager"
path = "bin/key_manager.rs"
required-features = ["key-manager"]

[features]
key-manager = ["ed25519-dalek"]
