[package]
name = "simag_core"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
float-cmp = "0.6.0"
nom = { version = "^2.1.0", features = ["verbose-errors"] }
chrono = "0.4.10"
rayon = "1.3.0"
num_cpus = "^1.12.0"
log = "0.4.8"
dashmap = "^3.2.0"
parking_lot = "0.10"

# own packages
simag_terminal = { path = "../simag_terminal" }

# optionals
once_cell = "^1.3.0"
env_logger = "0.7.1"

# bin deps
ansi_term = { version = "0.12.1", optional = true }

[features]
binaries = ["ansi_term"]

[[bin]]
name = "manager"
required-features = ["binaries"]
path = "src/bin/manager.rs"

[[bin]]
name = "repl"
required-features = ["binaries"]
path = "src/bin/repl.rs"
