[package]
name = "simag_core"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.11"
dashmap = "3.11.4"
env_logger = "0.7.1"
float-cmp = "0.8.0"
nom = { version = "6.0.0-alpha" }
num_cpus = "^1.12.0"
log = "0.4.8"
once_cell = "^1.3.0"
parking_lot = "0.11"
rayon = "1.3.1"
smallvec = "1.4.0"

simag_terminal = { path = "../simag_terminal" }

[dev-dependencies]
criterion = "^0.3.2"

[[bench]]
name = "repr"
harness = false
