[package]
name = "simag_core"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
edition = "2018"

[dependencies]
float-cmp = "0.8.0"
nom = { version = "6.0.0-alpha" }
chrono = "0.4.11"
rayon = "1.3.1"
num_cpus = "^1.12.0"
log = "0.4.8"
dashmap = "3.11.4"
parking_lot = "0.10"

# own packages
simag_terminal = { path = "../simag_terminal" }

# optionals
once_cell = "^1.3.0"
env_logger = "0.7.1"

# bin deps
ansi_term = { version = "0.12.1", optional = true }

[dev-dependencies]
criterion = "0.3"

[features]
binaries = ["ansi_term"]

[[bin]]
name = "manager"
required-features = ["binaries"]
path = "src/bin/manager.rs"

[[bin]]
name = "repl"
required-features = ["binaries"]
path = "src/bin/repl.rs"

[[bench]]
name = "repr"
harness = false
