[package]
name = "simag_term_utils"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
autobins = false
edition = "2018"

[dependencies]
copypasta = "0.7"
crossterm = "0.20"
tui = { version = "0.18", default-features = false, features = ['crossterm'] }

# internal
simag_core =  { path = "../simag_core" }

[[bin]]
name = "manager"
path = "bin/manager.rs"

[[bin]]
name = "repl"
path = "bin/repl.rs"
