[package]
name = "simag_terminal"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
autobins = false
edition = "2018"

[dependencies]
termion = "1.5.5"
once_cell = "1.4.0"
copypasta = "0.7.0"
