[package]
name = "simag_term"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
autobins = false
edition = "2018"

[dependencies]
nom = "^5.0.0"
termion = "^1.5.0"
ansi_term = "0.12.1"
once_cell = "1.2.0"
