[package]
name = "simag_term"
version = "0.0.1"
authors = ["Ignacio Duart Gómez <iduartgomez@gmail.com>"]
autobins = false
edition = "2018"

[dependencies]
termion = "1.5.0"
once_cell = "1.2.0"
copypasta = "0.6.0"
