[package]
name = "simag_core"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
float-cmp = "^0.2"
nom = { version = "^2.1", features = ["verbose-errors"] }
chrono = "^0.3"
rayon = "^1.0"
