[package]
name = "simag_core"
version = "0.0.1"
authors = ["IDG <iduartgomez@gmail.com>"]

[dependencies]
float-cmp = "^0.2.0"
nom = { version = "^2.1.0", features = ["verbose-errors"] }
chrono = "^0.4.0"
rayon = "^1.0.0"
